spring.application.name=springboot-webapp-template
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp